// <auto-generated />
using System;
using Accepta.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accepta.Api.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AcceptaContext))]
    [Migration("20260405033231_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("accepta")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accepta.Api.Common.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("email");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "accepta");
                });

            modelBuilder.Entity("Accepta.Api.Features.Merchants.Domain.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("address");

                    b.Property<string>("Country")
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_merchants");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_merchants_user_id");

                    b.ToTable("merchants", "accepta");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("alias");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar")
                        .HasColumnName("currency");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("MerchantId")
                        .HasColumnType("integer")
                        .HasColumnName("merchant_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_receipts");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_receipts_merchant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_receipts_user_id");

                    b.ToTable("receipts", "accepta");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.ReceiptItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_receipt_items");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_receipt_items_receipt_id");

                    b.ToTable("receipt_items", "accepta");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.ReceiptTax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_id");

                    b.HasKey("Id")
                        .HasName("pk_receipt_taxes");

                    b.HasIndex("ReceiptId")
                        .HasDatabaseName("ix_receipt_taxes_receipt_id");

                    b.ToTable("receipt_taxes", "accepta");
                });

            modelBuilder.Entity("Accepta.Api.Features.Merchants.Domain.Merchant", b =>
                {
                    b.HasOne("Accepta.Api.Common.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_merchants_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.Receipt", b =>
                {
                    b.HasOne("Accepta.Api.Features.Merchants.Domain.Merchant", "Merchant")
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_merchants_merchant_id");

                    b.HasOne("Accepta.Api.Common.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipts_users_user_id");

                    b.Navigation("Merchant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.ReceiptItem", b =>
                {
                    b.HasOne("Accepta.Api.Features.Receipts.Domain.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_items_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.ReceiptTax", b =>
                {
                    b.HasOne("Accepta.Api.Features.Receipts.Domain.Receipt", "Receipt")
                        .WithMany("Taxes")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_receipt_taxes_receipts_receipt_id");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Accepta.Api.Features.Receipts.Domain.Receipt", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
